module.exports.AUTO_UPDATE_EVENT = 'auto-update/event'
module.exports.AUTO_UPDATE_COMMAND = 'auto-update/command'
module.exports.NODE_EVENT = 'node/event'
module.exports.NODE_COMMAND = 'node/command'
module.exports.AI_SOLVER_COMMAND = 'ai-solver/command'
module.exports.AI_SOLVER_EVENT = 'ai-solver/event'
module.exports.AI_TEST_UNIT_COMMAND = 'ai-test-unit/command'
module.exports.AI_TEST_UNIT_EVENT = 'ai-test-unit/event'
